# remote_theme: pages-themes/leap-day@v0.2.0
# plugins:
#   - jekyll-remote-theme
title: DrNarika Actions
description: My Cute&Faithful Partner!!(When coding anytime!)

logo: /co-worker.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
