name: RSSFeedUpdate
on:
  # push:
  #   branches: [ "main" ]
  # schedule:
  #   - cron: "30 3 * * 0-6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup-workspace:
    name: Set-Up Workspace
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - name: clean workspace
        run: |
          rm -rf *
          rm -rf .[^.]*
      - name: pull repo
        run: |
          git clone https://github.com/drnarika/drnarika.github.io site
          mv -f ./site/.[^.]* .
          mv -f ./site/* .
          rm -rf site
      # - name: Checkout
      #   uses: actions/checkout@v4
  setup-updater:
    name: Set-Up RSS-Updater
    runs-on: self-hosted
    needs: setup-workspace
    timeout-minutes: 5
    steps:
      - name: make rss-updater working dir
        run: mkdir updater
      - name: clone down rss-updater
        run: git clone https://github.com/drnarika/rss-updater updater
      - name: copy sources from feed/sources
        run: cp -rf ./feed/sources/* ./updater/sources/
  update-feed:
    name: Updating RSS-Feed
    runs-on: self-hosted
    needs: setup-updater
    timeout-minutes: 15
    steps:
      - name: install requirements
        run: pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
        working-directory: ./updater
      - name: run main.py
        run: python ./src/main.py
        working-directory: ./updater
      # - name: check feedxml directory
      #   run: if [ ! -d "../feed/xml" ]; then mkdir ../feed/xml; fi
        # working-directory: ./updater
      - name: copy complete feeds
        run: cp -rf ./dist/* ../feed/xml/
        working-directory: ./updater
  cleaning-pushing:
    name: Cleaning & Pushing
    runs-on: self-hosted
    needs: update-feed
    timeout-minutes: 5
    env:
      RUN_ID: ${{ github.run_id }}
    steps:
      - name: cleaning updater
        run: rm -rf updater
      - name: Commit files
        run: |
          git add ./feed/xml/*
          git config --local user.email "drnarika@outlook.com"
          git config --local user.name "github-actions[bot]"
          check_results=`git status`
          if [[ $check_results =~ "nothing to commit" ]]
          then
              exit 0
          else
              git commit -a -m "RSS-Feed Update-$RUN_ID"
          fi
      - name: Push changes
        run: |
          git remote add ssh git@github.com:drnarika/drnarika.github.io
          git pull
          git push ssh